_target_: hvae.models.DCTHVAE
img_size: ${dataset.img_size}
in_channels: ${dataset.num_channels}
channels: [16, 32, 64, 128]
latent_dim: 16
beta: 4
ks: [64, 16, 8, 4]
lr: 0.0001
residual: false
num_classes: ${dataset.num_classes}